"""add indexes

Revision ID: 5916a74bc4e4
Revises: e15d3ab4f74d
Create Date: 2026-07-05 15:01:10.289676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5916a74bc4e4'
down_revision: Union[str, Sequence[str], None] = 'e15d3ab4f74d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_logs_url_id'), 'logs', ['url_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_logs_url_id'), table_name='logs')
    # ### end Alembic commands ###
